In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# Modeling lounge eligibility at Heathrow Terminal 3
data_set = pd.read_excel("British Airways Summer Schedule Dataset.xlsx")

In [3]:
data_set

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,A320,0,8,172,0,16,54
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,A320,0,13,167,0,6,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025-06-07,22:04:00,Evening,BA,BA7039,LHR,VIE,Austria,Europe,SHORT,A320,0,7,173,1,15,51
9996,2025-04-22,15:15:00,Afternoon,BA,BA9712,LHR,ORD,USA,North America,LONG,B777,8,49,178,1,0,0
9997,2025-08-16,06:11:00,Morning,BA,BA7513,LHR,HND,Japan,Asia,LONG,B777,0,32,304,0,4,19
9998,2025-10-24,22:02:00,Evening,BA,BA9958,LHR,DXB,UAE,Middle East,LONG,B787,8,48,200,1,10,38
9999,2025-05-28,22:00:00,Evening,BA,BA8374,LHR,DFW,USA,North America,LONG,B787,0,35,179,2,11,40

In [4]:
import io

In [5]:
data_content = pd.read_csv("British-Airways-Summer-Schedule-Dataset.csv")

In [6]:
data_content

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,9/2/2025,14:19,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,6/10/2025,6:42,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
2,10/27/2025,15:33,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40
3,6/15/2025,18:29,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,A320,0,8,172,0,16,54
4,8/25/2025,20:35,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,A320,0,13,167,0,6,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,6/7/2025,22:04,Evening,BA,BA7039,LHR,VIE,Austria,Europe,SHORT,A320,0,7,173,1,15,51
9996,4/22/2025,15:15,Afternoon,BA,BA9712,LHR,ORD,USA,North America,LONG,B777,8,49,178,1,0,0
9997,8/16/2025,6:11,Morning,BA,BA7513,LHR,HND,Japan,Asia,LONG,B777,0,32,304,0,4,19
9998,10/24/2025,22:02,Evening,BA,BA9958,LHR,DXB,UAE,Middle East,LONG,B787,8,48,200,1,10,38
9999,5/28/2025,22:00,Evening,BA,BA8374,LHR,DFW,USA,North America,LONG,B787,0,35,179,2,11,40

In [7]:
import io

In [8]:
import pandas as pd
import io

In [9]:
data_content.head(2)

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,9/2/2025,14:19,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,6/10/2025,6:42,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28

In [10]:
# Calculating the eligibility lookup table
"""
Analyzes the flight schedule data to create a lookup table of
average lounge eligibility percentages grouped by Route Haul and Time of Day.
"""
"""
1. Calculate Total Passengers (TOTAL_PAX): We sum the seats in all classes.
    # We use this as the total volume against which we calculate the eligibility percentages.
"""

df = data_content
df["TOTAL_PASS"] = df["FIRST_CLASS_SEATS"] + df["BUSINESS_CLASS_SEATS"] + df["ECONOMY_SEATS"]

In [35]:
df["TOTAL_PASS"]

0       235
1       235
2       180
3       180
4       180
       ...
9995    180
9996    235
9997    336
9998    256
9999    214
Name: TOTAL_PASS, Length: 10000, dtype: int64

In [16]:
# 2. Define the Grouping Key (FLIGHT_GROUP):
"""
This combines the two variables we believe influence eligibility most: Haul and Time of Day.
"""
df["FLIGHT_GROUP"] = df["HAUL"] + "-" + df["TIME_OF_DAY"]
df["FLIGHT_GROUP"].head()

0     LONG-Afternoon
1       LONG-Morning
2    SHORT-Afternoon
3      SHORT-Evening
4      SHORT-Evening
Name: FLIGHT_GROUP, dtype: object

In [11]:
df.head(2)

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX,TOTAL_PASS
0,9/2/2025,14:19,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38,235
1,6/10/2025,6:42,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28,235

In [23]:
# 3. The Aggregation and Calculation of Percentages
# Group the entire DataFrame by the new FLIGHT_GROUP key and sum the important columns.
grouped = df.groupby("FLIGHT_GROUP").agg(
    Total_Pax_Volume = ("TOTAL_PASS", "sum"), # sum of all passengers volume(seats)
    Total_Tier1_Eligible = ("TIER1_ELIGIBLE_PAX", "sum"), # sum of all Tier1 eligible Pax in the group
    Total_Tier2_Eligible = ("TIER2_ELIGIBLE_PAX", "sum"), # sum of all Tier2 eligible Pax in the group
    Total_Tier3_Eligible = ("TIER3_ELIGIBLE_PAX", "sum"), # sum of all Tier3 eligible Pax in the group
    Flight_Count = ("FLIGHT_GROUP", "size"), # Count how many flights are in the group.
)

In [24]:
 # 4. Calculate the average number of passengers per flight in this group (for context)
grouped["Avg_Pax_Per_Flight"] = (grouped["Total_Pax_Volume"] / grouped["Flight_Count"]).round(0).astype(int)

In [32]:
# 5. Calculate the Eligibility Percentage for each tier:
# This is the core assumption: (Total Eligible Pax) / (Total Pax Volume) * 100
grouped["Tier1_Eligibility_Pct"] = (grouped["Total_Tier1_Eligible"] / grouped["Total_Pax_Volume"]) * 100
grouped["Tier2_Eligibility_Pct"] = (grouped["Total_Tier2_Eligible"] / grouped["Total_Pax_Volume"]) * 100
grouped["Tier3_Eligibility_Pct"] = (grouped["Total_Tier3_Eligible"] / grouped["Total_Pax_Volume"]) * 100

In [48]:
# Select the columns that form the final, clean lookup table
lookup_table = grouped[[
        "Avg_Pax_Per_Flight",
        "Tier1_Eligibility_Pct",
        "Tier2_Eligibility_Pct",
        "Tier3_Eligibility_Pct"
    ]].sort_index()  # Sort by the grouping name (A-Z)

In [42]:
grouped["Tier1_Eligibility_Pct"]

FLIGHT_GROUP
LONG-Afternoon     0.198372
LONG-Evening       0.212001
LONG-Lunchtime     0.176841
LONG-Morning       0.205362
SHORT-Afternoon    0.341630
SHORT-Evening      0.328410
SHORT-Lunchtime    0.394100
SHORT-Morning      0.339939
Name: Tier1_Eligibility_Pct, dtype: float64

In [55]:
def create_lookup_table(data_content):
    """
    Function to create a lookup table for eligibility percentages.
    The total volume against which we calculate the eligibility percentages.
    """

    df = data_content
    df["TOTAL_PASS"] = df["FIRST_CLASS_SEATS"] + df["BUSINESS_CLASS_SEATS"] + df["ECONOMY_SEATS"]

    # 2. Define the Grouping Key (FLIGHT_GROUP):
    """
    This combines the two variables we believe influence eligibility most: Haul and Time of Day.
    """
    df["FLIGHT_GROUP"] = df["HAUL"] + "-" + df["TIME_OF_DAY"]

    # 3. The Aggregation and Calculation of Percentages
    # Group the entire DataFrame by the new FLIGHT_GROUP key and sum the important columns.
    grouped = df.groupby("FLIGHT_GROUP").agg(
        Total_Pax_Volume = ("TOTAL_PASS", "sum"), # sum of all passengers volume(seats)
        Total_Tier1_Eligible = ("TIER1_ELIGIBLE_PAX", "sum"), # sum of all Tier1 eligible Pax in the group
        Total_Tier2_Eligible = ("TIER2_ELIGIBLE_PAX", "sum"), # sum of all Tier2 eligible Pax in the group
        Total_Tier3_Eligible = ("TIER3_ELIGIBLE_PAX", "sum"), # sum of all Tier3 eligible Pax in the group
        Flight_Count = ("FLIGHT_GROUP", "size"), # Count how many flights are in the group.
    )

    # 4. Calculate the average number of passengers per flight in this group (for context)
    grouped["Avg_Pax_Per_Flight"] = (grouped["Total_Pax_Volume"] / grouped["Flight_Count"]).round(0).astype(int)

    # 5. Calculate the Eligibility Percentage for each tier:
    # This is the core assumption: (Total Eligible Pax) / (Total Pax Volume) * 100
    grouped["Tier1_Eligibility_Pct"] = (grouped["Total_Tier1_Eligible"] / grouped["Total_Pax_Volume"]) * 100
    grouped["Tier2_Eligibility_Pct"] = (grouped["Total_Tier2_Eligible"] / grouped["Total_Pax_Volume"]) * 100
    grouped["Tier3_Eligibility_Pct"] = (grouped["Total_Tier3_Eligible"] / grouped["Total_Pax_Volume"]) * 100

    # Select the columns that form the final, clean lookup table
    lookup_table = grouped[[
            "Avg_Pax_Per_Flight",
            "Tier1_Eligibility_Pct",
            "Tier2_Eligibility_Pct",
            "Tier3_Eligibility_Pct"
        ]].sort_index()  # Sort by the grouping name (A-Z)

    return lookup_table

In [56]:
print(lookup_table)

                 Avg_Pax_Per_Flight  Tier1_Eligibility_Pct  \
FLIGHT_GROUP
LONG-Afternoon                  293               0.198372
LONG-Evening                    292               0.212001
LONG-Lunchtime                  290               0.176841
LONG-Morning                    292               0.205362
SHORT-Afternoon                 180               0.341630
SHORT-Evening                   180               0.328410
SHORT-Lunchtime                 180               0.394100
SHORT-Morning                   180               0.339939

                 Tier2_Eligibility_Pct  Tier3_Eligibility_Pct
FLIGHT_GROUP
LONG-Afternoon                2.765564              10.521373
LONG-Evening                  2.674498              10.264195
LONG-Lunchtime                2.710504              10.383658
LONG-Morning                  2.789037              10.632896
SHORT-Afternoon               4.313486              16.587360
SHORT-Evening                 4.451611              16.995700
SHORT-Lunchtime               4.548657              17.275062
SHORT-Morning                 4.357983              16.742925

In [58]:
df.head(2)

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX,TOTAL_PASS,FLIGHT_GROuP,FLIGHT_GROUP
0,9/2/2025,14:19,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38,235,LONG-Afternoon,LONG-Afternoon
1,6/10/2025,6:42,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28,235,LONG-Morning,LONG-Morning

In [59]:
df.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   FLIGHT_DATE           10000 non-null  object
 1   FLIGHT_TIME           10000 non-null  object
 2   TIME_OF_DAY           10000 non-null  object
 3   AIRLINE_CD            10000 non-null  object
 4   FLIGHT_NO             10000 non-null  object
 5   DEPARTURE_STATION_CD  10000 non-null  object
 6   ARRIVAL_STATION_CD    10000 non-null  object
 7   ARRIVAL_COUNTRY       10000 non-null  object
 8   ARRIVAL_REGION        10000 non-null  object
 9   HAUL                  10000 non-null  object
 10  AIRCRAFT_TYPE         10000 non-null  object
 11  FIRST_CLASS_SEATS     10000 non-null  int64
 12  BUSINESS_CLASS_SEATS  10000 non-null  int64
 13  ECONOMY_SEATS         10000 non-null  int64
 14  TIER1_ELIGIBLE_PAX    10000 non-null  int64
 15  TIER2_ELIGIBLE_PAX    10000 non-null  int64
 16  TIER3_ELIGIBLE_PAX    10000 non-null  int64
 17  TOTAL_PASS            10000 non-null  int64
 18  FLIGHT_GROuP          10000 non-null  object
 19  FLIGHT_GROUP          10000 non-null  object
dtypes: int64(7), object(13)
memory usage: 1.5+ MB

In [77]:
df.groupby(["ARRIVAL_COUNTRY"]).sum().sort_values(by = "FLIGHT_GROUP", ascending = False)

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX,TOTAL_PASS,FLIGHT_GROuP,FLIGHT_GROUP
ARRIVAL_COUNTRY,,,,,,,,,,,,,,,,,,,
Spain,6/1/202510/5/20258/24/20259/3/20259/22/20256/1...,10:2718:5919:286:0022:0411:2810:4922:4316:4311...,MorningEveningEveningMorningEveningMorningMorn...,BABABABABABABABABABABABABABABABABABABABABABABA...,BA1302BA9311BA9976BA6358BA5207BA4358BA2572BA74...,LHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRL...,MADMADMADBCNMADMADMADBCNMADBCNBCNMADMADBCNMADB...,EuropeEuropeEuropeEuropeEuropeEuropeEuropeEuro...,SHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTS...,A320A320A320A320A320A320A320A320A320A320A320A3...,0,13242,223998,790,10458,40009,237240,SHORT-MorningSHORT-EveningSHORT-EveningSHORT-M...,SHORT-MorningSHORT-EveningSHORT-EveningSHORT-M...
Switzerland,9/2/20259/27/20258/9/20256/24/20256/26/20257/2...,6:4816:1214:5410:4312:1618:0114:497:4510:096:5...,MorningAfternoonAfternoonMorningLunchtimeEveni...,BABABABABABABABABABABABABABABABABABABABABABABA...,BA8555BA9861BA4309BA2950BA1087BA9781BA3385BA11...,LHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRL...,ZRHZRHZRHZRHZRHZRHZRHZRHZRHZRHZRHZRHZRHZRHZRHZ...,EuropeEuropeEuropeEuropeEuropeEuropeEuropeEuro...,SHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTS...,A320A320A320A320A320A320A320A320A320A320A320A3...,0,6244,108596,392,4994,19255,114840,SHORT-MorningSHORT-AfternoonSHORT-AfternoonSHO...,SHORT-MorningSHORT-AfternoonSHORT-AfternoonSHO...
Netherlands,9/16/20258/23/20255/28/20256/3/20255/3/20259/2...,21:449:276:0516:3112:4513:4417:4217:2920:4420:...,EveningMorningMorningAfternoonLunchtimeLunchti...,BABABABABABABABABABABABABABABABABABABABABABABA...,BA9840BA8924BA1683BA9353BA8214BA8831BA9584BA72...,LHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRL...,AMSAMSAMSAMSAMSAMSAMSAMSAMSAMSAMSAMSAMSAMSAMSA...,EuropeEuropeEuropeEuropeEuropeEuropeEuropeEuro...,SHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTS...,A320A320A320A320A320A320A320A320A320A320A320A3...,0,6606,108774,366,5139,19608,115380,SHORT-EveningSHORT-MorningSHORT-MorningSHORT-A...,SHORT-EveningSHORT-MorningSHORT-MorningSHORT-A...
Turkey,6/15/20255/1/20256/14/20256/1/202510/20/20259/...,18:299:5514:1615:2821:1119:5011:258:3619:3910:...,EveningMorningAfternoonAfternoonEveningEvening...,BABABABABABABABABABABABABABABABABABABABABABABA...,BA5497BA4878BA8994BA4414BA6423BA6576BA1456BA84...,LHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRL...,ISTISTISTISTISTISTISTISTISTISTISTISTISTISTISTI...,EuropeEuropeEuropeEuropeEuropeEuropeEuropeEuro...,SHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTS...,A320A320A320A320A320A320A320A320A320A320A320A3...,0,6485,110515,457,5239,20007,117000,SHORT-EveningSHORT-MorningSHORT-AfternoonSHORT...,SHORT-EveningSHORT-MorningSHORT-AfternoonSHORT...
France,6/2/20256/13/20257/3/20256/21/20256/4/20257/7/...,22:3714:2012:1813:3111:2918:3812:1722:0718:219...,EveningAfternoonLunchtimeLunchtimeMorningEveni...,BABABABABABABABABABABABABABABABABABABABABABABA...,BA3129BA3998BA3137BA1676BA3697BA5241BA8150BA35...,LHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRL...,CDGCDGCDGCDGCDGCDGCDGCDGCDGCDGCDGCDGCDGCDGCDGC...,EuropeEuropeEuropeEuropeEuropeEuropeEuropeEuro...,SHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTS...,A320A320A320A320A320A320A320A320A320A320A320A3...,0,6641,108739,372,5036,19331,115380,SHORT-EveningSHORT-AfternoonSHORT-LunchtimeSHO...,SHORT-EveningSHORT-AfternoonSHORT-LunchtimeSHO...
Austria,7/12/20256/13/20258/2/20257/22/20259/9/20256/2...,19:0814:5717:4810:016:3514:2118:3311:3713:279:...,EveningAfternoonAfternoonMorningMorningAfterno...,BABABABABABABABABABABABABABABABABABABABABABABA...,BA4954BA7734BA9842BA3246BA6502BA2271BA5931BA12...,LHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRL...,VIEVIEVIEVIEVIEVIEVIEVIEVIEVIEVIEVIEVIEVIEVIEV...,EuropeEuropeEuropeEuropeEuropeEuropeEuropeEuro...,SHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTS...,A320A320A320A320A320A320A320A320A320A320A320A3...,0,6952,115808,445,5065,19669,122760,SHORT-EveningSHORT-AfternoonSHORT-AfternoonSHO...,SHORT-EveningSHORT-AfternoonSHORT-AfternoonSHO...
Germany,10/27/20258/25/20255/17/20255/10/20255/27/2025...,15:3320:3512:1310:1120:216:2514:0516:008:056:5...,AfternoonEveningLunchtimeMorningEveningMorning...,BABABABABABABABABABABABABABABABABABABABABABABA...,BA1896BA1493BA4424BA8213BA3986BA4218BA4192BA99...,LHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRL...,FRAFRAFRAMUCMUCFRAMUCFRAMUCMUCFRAFRAMUCFRAFRAF...,EuropeEuropeEuropeEuropeEuropeEuropeEuropeEuro...,SHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTSHORTS...,A320A320A320A320A320A320A320A320A320A320A320A3...,0,13756,239144,875,11390,43345,252900,SHORT-AfternoonSHORT-EveningSHORT-LunchtimeSHO...,SHORT-AfternoonSHORT-EveningSHORT-LunchtimeSHO...
Japan,5/22/202510/16/20259/14/20255/17/20256/4/20256...,6:2318:2916:4011:266:397:2915:4214:456:2111:17...,MorningEveningAfternoonMorningMorningMorningAf...,BABABABABABABABABABABABABABABABABABABABABABABA...,BA7992BA6458BA5518BA2207BA8602BA2517BA3001BA60...,LHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRL...,HNDHNDHNDHNDHNDHNDHNDHNDHNDHNDHNDHNDHNDHNDHNDH...,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,LONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLO...,B787B777A380B787B777B787A350B777A380B777A380B7...,2576,32068,162711,379,5325,20430,197355,LONG-MorningLONG-EveningLONG-AfternoonLONG-Mor...,LONG-MorningLONG-EveningLONG-AfternoonLONG-Mor...
USA,9/2/20256/10/20254/24/20259/2/20254/2/20256/5/...,14:196:4214:507:4817:0422:2817:3718:596:298:49...,AfternoonMorningAfternoonMorningAfternoonEveni...,BABABABABABABABABABABABABABABABABABABABABABABA...,BA5211BA7282BA7116BA8942BA8677BA9080BA2199BA33...,LHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRL...,LAXLAXORDLAXORDJFKJFKORDJFKORDJFKLAXORDJFKLAXL...,North AmericaNorth AmericaNorth AmericaNorth A...,LONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLO...,B777B777A350B777B787B777A380B777B787B777B787B7...,10286,126509,639772,1589,21470,81912,776567,LONG-AfternoonLONG-MorningLONG-AfternoonLONG-M...,LONG-AfternoonLONG-MorningLONG-AfternoonLONG-M...
UAE,4/10/20254/25/20258/28/202510/27/20259/27/2025...,16:0420:0622:2911:1019:1610:566:3913:1719:4920...,AfternoonEveningEveningMorningEveningMorningMo...,BABABABABABABABABABABABABABABABABABABABABABABA...,BA1609BA3990BA9466BA2032BA9424BA1547BA2419BA62...,LHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRLHRL...,DXBDXBDXBDXBDXBDXBDXBDXBDXBDXBDXBDXBDXBDXBDXBD...,Middle EastMiddle EastMiddle EastMiddle EastMi...,LONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLONGLO...,B787B777B787B777B787B787B777B787A380B777B777B7...,2610,32235,165802,412,5403,20648,200647,LONG-AfternoonLONG-EveningLONG-EveningLONG-Mor...,LONG-AfternoonLONG-EveningLONG-EveningLONG-Mor...

In [69]:
df[["HAUL", "ARRIVAL_COUNTRY"]]

       HAUL ARRIVAL_COUNTRY
0      LONG             USA
1      LONG             USA
2     SHORT         Germany
3     SHORT          Turkey
4     SHORT         Germany
...     ...             ...
9995  SHORT         Austria
9996   LONG             USA
9997   LONG           Japan
9998   LONG             UAE
9999   LONG             USA

[10000 rows x 2 columns]

In [78]:
df[["ARRIVAL_STATION_CD", "ARRIVAL_COUNTRY", "FLIGHT_GROUP"]]

     ARRIVAL_STATION_CD ARRIVAL_COUNTRY     FLIGHT_GROUP
0                   LAX             USA   LONG-Afternoon
1                   LAX             USA     LONG-Morning
2                   FRA         Germany  SHORT-Afternoon
3                   IST          Turkey    SHORT-Evening
4                   FRA         Germany    SHORT-Evening
...                 ...             ...              ...
9995                VIE         Austria    SHORT-Evening
9996                ORD             USA   LONG-Afternoon
9997                HND           Japan     LONG-Morning
9998                DXB             UAE     LONG-Evening
9999                DFW             USA     LONG-Evening

[10000 rows x 3 columns]